services:
  listener-service:
    platform: linux/amd64
    image: "wiliehidayat87/testmq-listener:latest"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 9022:9022
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Users/wiliewahyuhidayat/Documents/GO/testMQ/logs:/Users/wiliewahyuhidayat/Documents/GO/testMQ/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"