version: '3.7'

services:
  rabbit1:
    image: bitnami/rabbitmq:latest
    container_name: rabbit1Sample
    hostname: rabbit1
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
