services:
  publisher-service:
    image: "wiliehidayat87/testmq-publisher:latest"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 9021:9021
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Users/wiliewahyuhidayat/Documents/GO/testMQ/logs:/Users/wiliewahyuhidayat/Documents/GO/testMQ/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"