version: "3.3"

services:
  listener-service:
    image: "wiliehidayat87/testmq-listener:latest"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 9022:9022
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"