name: CI

on: 
    push:
        branches: ["main"]
        tags: 
            - 'v*'
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - 
                        dockerfile: ./Dockerfile.listener
                        image: wiliehidayat87/testmq-listener
                    - 
                        dockerfile: ./Dockerfile.consumer
                        image: wiliehidayat87/testmq-consumer

                    - 
                        dockerfile: ./Dockerfile.publisher
                        image: wiliehidayat87/testmq-publisher
                        
        permissions:
            contents: read
            packages: write

        steps:
        -
            name: Checkout
            uses: actions/checkout@v3

        -
            name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ matrix.image }}
                tags: |
                    type=raw,value=latest,enable={{is_default_branch}}
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        -
            name: Build and push
            run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push .